-- MySQL Script generated by MySQL Workbench
-- jue 21 abr 2016 23:20:19 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lease_control_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lease_control_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lease_control_system` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `lease_control_system` ;

-- -----------------------------------------------------
-- Table `lease_control_system`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lease_control_system`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `pw_hash` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `gender` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lease_control_system`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lease_control_system`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lease_control_system`.`rel_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lease_control_system`.`rel_user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lease_control_system`.`property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lease_control_system`.`property` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `type_id` INT NOT NULL,
  `lessor_id` INT NOT NULL,
  `property_group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lease_control_system`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lease_control_system`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenant_id` INT NOT NULL,
  `holder_id` INT NOT NULL,
  `lessor_id` INT NOT NULL,
  `property_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `solved` TINYINT(1) NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `text` TEXT NOT NULL,
  `sent_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lease_control_system`.`message_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lease_control_system`.`message_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lease_control_system`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lease_control_system`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `lessor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lease_control_system`.`property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lease_control_system`.`property` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `type_id` INT NOT NULL,
  `lessor_id` INT NOT NULL,
  `property_group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lease_control_system`.`property_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lease_control_system`.`property_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lease_control_system`.`rel_rent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lease_control_system`.`rel_rent` (
  `property_id` INT NOT NULL,
  `tenant_id` INT NOT NULL,
  `holder_id` INT NOT NULL,
  `lessor_id` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
